### ISSUE TITLE
Failed to build cfunc_filter.cu.o

### ISSUE THREAD

**Issue by cmoon4** [tomography/tomocupy-cli#19]
Hello,

I'm trying to follow the installation guide from https://tomocupy.readthedocs.io/en/latest/install.html# and facing an error on the installation step. It looks like it's failing at building cfunc_filter.cu.o, though I could be wrong about that. I have pasted the error output when I try to install below.

[tomocupy]$ python setup.py install
/home/cmoon/anaconda3/envs/tomocupy/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
[8/10] Building CUDA object src/cuda/CMakeFiles/cfunc_filterfp16.dir/cfunc_filter.cu.o
FAILED: src/cuda/CMakeFiles/cfunc_filterfp16.dir/cfunc_filter.cu.o 
/home/cmoon/anaconda3/envs/tomocupy/bin/nvcc -forward-unknown-to-host-compiler -DHALF -Dcfunc_filterfp16_EXPORTS -I/home/cmoon/tomocupy/src/include -I/home/cmoon/anaconda3/envs/tomocupy/include -I/home/cmoon/anaconda3/envs/tomocupy/include/python3.10 -O3 -DNDEBUG --generate-code=arch=compute_60,code=[compute_60,sm_60] --generate-code=arch=compute_72,code=[compute_72,sm_72] --generate-code=arch=compute_75,code=[compute_75,sm_75] --generate-code=arch=compute_80,code=[compute_80,sm_80] -Xcompiler=-fPIC -std=c++03 -MD -MT src/cuda/CMakeFiles/cfunc_filterfp16.dir/cfunc_filter.cu.o -MF src/cuda/CMakeFiles/cfunc_filterfp16.dir/cfunc_filter.cu.o.d -x cu -c /home/cmoon/tomocupy/src/cuda/cfunc_filter.cu -o src/cuda/CMakeFiles/cfunc_filterfp16.dir/cfunc_filter.cu.o
/home/cmoon/tomocupy/src/include/cfunc_filter.cuh(10): warning #2512-D: field initializers are a C++11 feature

/home/cmoon/tomocupy/src/cuda/cfunc_filter.cu(10): error: more than one instance of overloaded function "log2" matches the argument list:
            function "log2(double)"
/home/cmoon/anaconda3/envs/tomocupy/include/crt/math_functions.h(894): here
            function "log2(float)"
/home/cmoon/anaconda3/envs/tomocupy/include/crt/math_functions.hpp(617): here
            argument types are: (unsigned long)

1 error detected in the compilation of "/home/cmoon/tomocupy/src/cuda/cfunc_filter.cu".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/cmoon/anaconda3/envs/tomocupy/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/home/cmoon/anaconda3/envs/tomocupy/lib/python3.10/site-packages/skbuild/cmaker.py", line 680, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/home/cmoon/anaconda3/envs/tomocupy/lib/python3.10/site-packages/skbuild/cmaker.py", line 704, in make_impl
    raise SKBuildError(

An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release --
  Install target:
    install
  Source directory:
    /home/cmoon/tomocupy
  Working directory:
    /home/cmoon/tomocupy/_skbuild/linux-x86_64-3.10/cmake-build
Please check the install target is valid and see CMake's output for more information.

**Comment by nikitinvv** [comment]
@cmoon4 what is your GPU and cuda toolkit /driver version?

**Comment by cmoon4** [comment]
Here are the outputs of nvidia-smi and nvcc --version

(tomocupy) [cmoon@p075196 tomocupy]$ nvidia-smi
Tue Sep 27 19:22:44 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.57       Driver Version: 515.57       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:07:00.0  On |                  Off |
| 30%   42C    P8    28W / 300W |    146MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2024      G   /usr/bin/X                         65MiB |
|    0   N/A  N/A      9516      G   /usr/bin/gnome-shell               75MiB |
+-----------------------------------------------------------------------------+


(tomocupy) [cmoon@p075196 tomocupy]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

**Comment by cmoon4** [comment]
Sorry, accidentally closed the issue. Here are the outputs from nvidia-smi and nvcc --version


```
(tomocupy) [cmoon@p075196 tomocupy]$ nvidia-smi
Tue Sep 27 19:22:44 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.57       Driver Version: 515.57       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:07:00.0  On |                  Off |
| 30%   42C    P8    28W / 300W |    146MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2024      G   /usr/bin/X                         65MiB |
|    0   N/A  N/A      9516      G   /usr/bin/gnome-shell               75MiB |
+-----------------------------------------------------------------------------+

```

```
(tomocupy) [cmoon@p075196 tomocupy]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

**Comment by nikitinvv** [comment]
@cmoon4 please check the updated version of the code

**Comment by cmoon4** [comment]
That worked! Now it builds correctly and runs through the test_all script without any issues. Thank you for your help!
